// Generado: nombres reales de objeto (de los modelos/iconos 08* del cliente)
// Usado por servidor_mundo OBJECTINFO para que la ficha muestre nombres reales.
#pragma once
static const char* NOMBRES_OBJETO[] = {
    "Anillo","Anzuelo","Arandela","Arcon","Ases","Azulejo","Bala","Ballesta","Basket",
    "Berenjena","Billete","Bola","Bolablanca","Bolsa","Bomba","Bombona","Bone","Bonebolsa",
    "Bonsai","Botella","Brazalete","Cabeza","Cabezaguardia","Cables","Cadena","Caja",
    "Cajapistola","Cajita","Calabacin","Calcetines","Calculadora","Calendario","Calzon",
    "Camara","Candybar","Capsula","Capucha","Cargador","Cargadoruzi","Carta","Cartas","Cartera",
    "Cartuchos","Casco","Cepillo","Cerrojo","Cerveza","Cesped","Champan","Chapa","Chapita",
    "Chili","Chocolate","Cinta","Cintu","Cinturon","Clavo","Cobre","Cocktel","Cofre","Compas",
    "Compresa","Condon","Condonamarillo","Condonazul","Condongris","Condonrojo","Copachoco",
    "Cuaderno","Cubo","Cuchillo","Cuerda","Dado","Daga","Destornillador","Dildo","Doblones",
    "Egipto","Espadas","Espejo","Esposas","Estampita","Extintor","Extintorgoma","Figuracamello",
    "Figuraciervo","Figuraelefante","Figuralobo","Figurarino","Figuratigre","Flecha","Frasco",
    "Futbol","Gafas","Galletas","Ganzuas","Garrafa","Golf","Gorro","Grapadora","Grial",
    "Guantecirugia","Guantes","Guisante","Gusano","Hacha","Hojaarbol","Hongos","Insignia",
    "Insigniaoso","Jabon","Jarron","Katana","Lanza","Lata","Leotardos","Libro","Linterna",
    "Llave","Llavecripta","Llaveing","Llavequebrada","Maderag","Maleta","Mangas","Mangofilo",
    "Mano","Mapa","Mapamuni","Mariposa","Martillo","Mascara","Maza","Mecha","Mechero",
    "Medallon","Mercromina","Metro","Moldellave","Moneda","Monedaan","Montoncito","Mosqueton",
    "Movilcarga","Navaja","Nota","Pantalon","Pastel","Pastilla","Patito","Perla","Perlanegra",
    "Petardo","Peto","Piedraazul","Piedragris","Pieza","Pila","Pildora","Pimiento","Pistola",
    "Pistolababycompact","Pistolac04c","Pistolaca","Pistolacompanion","Pistolaglock",
    "Pistolaha116s","Pistolahunter","Pistolahwc","Pistolaindian","Pistolamp","Pistolamri",
    "Pistolap","Pistolasigp","Pistolasp22m","Pistolassp","Pistolcrossman","Pistoldaisy",
    "Pistoleagle","Pistolflintlock355_69cal","Pistoljackal","Pistoluzisporter","Pistolyugom",
    "Placa1e","Placa1n","Placa1s","Placa1w","Placa2e","Placa2n","Placa2s","Placa2w","Placa3n",
    "Placa3s","Placa3w","Placa4e","Placa4n","Placa4s","Placa4w","Placae","Plancharara","Plato",
    "Platolaminas","Pluma","Pocion","Pomada","Pombagira","Porra","Prismaticos","Radio",
    "Radioantigua","Radiografia","Refresco","Regalo","Regla","Rejas","Reloj","Relojesquema",
    "Revista","Revolversmithwesson","Rifle","Rodilleras","Rollo","Rollopeli","Rounds","Rugby",
    "Ruleta","Sagrario","Salami","Serrucho","Shells","Slash","Solmedallon","Sombrero","Spray",
    "Sprayplata","Supositorio","Swordmango","Tarjeta","Taza","Tijeras","Tomate","Tornillo",
    "Trozometal","Tuerca","Urna","Uziametralla","Uzideoro","Vara","Velascumple","Vendas",
    "Vibrador","Virgen","Virgenboss","Zanahorias","Zapatos",
};
